CREATE TABLE "ADMIN"."CLIENT"
  (
    "CLIENT_ID"       NUMBER(*,0) NOT NULL ENABLE ,
    "CLIENT_NAME"     VARCHAR2(200 BYTE) NOT NULL ENABLE ,
    "CLIENT_EMAIL"    VARCHAR2(200 BYTE) NOT NULL ENABLE ,
    "PHONE_NUMBER"    VARCHAR2(200 BYTE) NOT NULL ENABLE ,
    "CLIENT_TYPE"     VARCHAR2(20 BYTE) NOT NULL ENABLE ,
    "CLIENT_COMMENT"  VARCHAR2(1000 BYTE) ,
    "HAS_PREFERENCES" VARCHAR2(200 BYTE) ,
    CONSTRAINT "CLIENT_ID_PK" PRIMARY KEY ("CLIENT_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "SYSTEM" ;
COMMENT ON COLUMN "ADMIN"."CLIENT"."CLIENT_ID"
IS
  'CUSTOMER_ID - ÜGYFÉL EGYEDI AZONOSÍTÓ';
  COMMENT ON COLUMN "ADMIN"."CLIENT"."CLIENT_NAME"
IS
  'ÜGYFÉL NÉV';
  COMMENT ON COLUMN "ADMIN"."CLIENT"."CLIENT_EMAIL"
IS
  'ÜGYFÉL E-MAIL CÍME';
  COMMENT ON COLUMN "ADMIN"."CLIENT"."PHONE_NUMBER"
IS
  'ÜGYFÉL TELEFONSZÁMA';
  COMMENT ON COLUMN "ADMIN"."CLIENT"."CLIENT_TYPE"
IS
  'ÜGYFÉL TÍPUS (ELADÓ/KERESŐ)';
  COMMENT ON COLUMN "ADMIN"."CLIENT"."CLIENT_COMMENT"
IS
  'ÜGYFÉL KOMENT';
  COMMENT ON COLUMN "ADMIN"."CLIENT"."HAS_PREFERENCES"
IS
  'Vannak-e ügyfél preferenciák';
  CREATE TABLE "ADMIN"."USER_DATA"
    (
      "USER_ID"  NUMBER(*,0) NOT NULL ENABLE ,
      "NAME"     VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "PASSWORD" VARCHAR2(256 BYTE) NOT NULL ENABLE ,
      "EMAIL"    VARCHAR2(80 CHAR) NOT NULL ENABLE ,
      "STATUS"   VARCHAR2(10 BYTE) NOT NULL ENABLE ,
      CONSTRAINT "USER_ID_PK" PRIMARY KEY ("USER_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE
    )
    SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "SYSTEM" ;
  COMMENT ON COLUMN "ADMIN"."USER_DATA"."USER_ID"
IS
  'USER_ID egyedi azonosítóval';
  COMMENT ON COLUMN "ADMIN"."USER_DATA"."NAME"
IS
  'Felhasználó neve';
  COMMENT ON COLUMN "ADMIN"."USER_DATA"."PASSWORD"
IS
  'Felhasználó jelszava SHA-256 hasheléssel';
  COMMENT ON COLUMN "ADMIN"."USER_DATA"."EMAIL"
IS
  'Felhasználó e-mail címe';
  COMMENT ON COLUMN "ADMIN"."USER_DATA"."STATUS"
IS
  'Felhasználó státusza';
  CREATE TABLE "ADMIN"."PROPERTY"
    (
      "PROPERTY_ID"        NUMBER(*,0) NOT NULL ENABLE ,
      "CLIENT_ID"          NUMBER NOT NULL ENABLE ,
      "USER_ID"            NUMBER NOT NULL ENABLE ,
      "PROPERTY_TYPE"      VARCHAR2(20 CHAR) NOT NULL ENABLE ,
      "PROPERTY_SIZE"      NUMBER(*,0) NOT NULL ENABLE ,
      "GROUND_SIZE"        NUMBER DEFAULT 0 NOT NULL ENABLE ,
      "NUMBER_OF_ROOMS"    NUMBER NOT NULL ENABLE ,
      "NUMBER_OF_HALFROOM" NUMBER NOT NULL ENABLE ,
      "PRICE"              NUMBER NOT NULL ENABLE ,
      "STREET_AND_NUMBER"  VARCHAR2(200 CHAR) NOT NULL ENABLE ,
      "CITY"               VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "MATERIAL"           VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "WC"                 VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "ENERGETIC_LEVEL"    VARCHAR2(20 BYTE) NOT NULL ENABLE ,
      "PROPERTY_CONDITION" VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "DESCRIPTION"        VARCHAR2(1000 CHAR) ,
      "AD_STATUS"          VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "COUNT_NUMBER"       NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE ,
      CONSTRAINT "PROPERTY_ID_PK" PRIMARY KEY ("PROPERTY_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE ,
      CONSTRAINT "USER_FK" FOREIGN KEY ("USER_ID") REFERENCES "ADMIN"."USER_DATA" ("USER_ID") ENABLE ,
      CONSTRAINT "CLIENT_FK" FOREIGN KEY ("CLIENT_ID") REFERENCES "ADMIN"."CLIENT" ("CLIENT_ID") ENABLE
    )
    SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "SYSTEM" ;
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."PROPERTY_ID"
IS
  'Ingatlan egyedi azonosító';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."CLIENT_ID"
IS
  'Ügyfél azonosító';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."USER_ID"
IS
  'Felhasználó azonosító';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."PROPERTY_TYPE"
IS
  'Cím típusa (Lakás, ház, telek, stb)';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."PROPERTY_SIZE"
IS
  'Az ingatlan mérete(négyzetméterben)';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."GROUND_SIZE"
IS
  'Telek méret(négyzetméter), Háznél és irodánál!';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."NUMBER_OF_ROOMS"
IS
  'Szobák száma';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."NUMBER_OF_HALFROOM"
IS
  'Félszobák száma';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."PRICE"
IS
  'Ár';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."STREET_AND_NUMBER"
IS
  'Cím';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."CITY"
IS
  'Város';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."MATERIAL"
IS
  'Ingatlan anyaga';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."WC"
IS
  'WC';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."ENERGETIC_LEVEL"
IS
  'Energetikai besorolás';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."PROPERTY_CONDITION"
IS
  'Ingatlan állapota (Új építés, felújított, felújítandó, stb)';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."DESCRIPTION"
IS
  'Ingatlan leírás';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."AD_STATUS"
IS
  'Hirdetés státusza';
  COMMENT ON COLUMN "ADMIN"."PROPERTY"."COUNT_NUMBER"
IS
  'Nézettség';
  CREATE TABLE "ADMIN"."SEARCH_PROPERTY"
    (
      "SEARCH_ID"     NUMBER NOT NULL ENABLE ,
      "CLIENT_ID"     NUMBER NOT NULL ENABLE ,
      "PROPERTY_TYPE" VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "SIZE_MIN"      VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "SIZE_MAX"      VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "PRICE_MIN"     VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "PRICE_MAX"     VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "SEARCH_TYPE"   VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "CITY"          VARCHAR2(200 BYTE) NOT NULL ENABLE ,
      "KEYWORD_ONE"   VARCHAR2(200 CHAR) NOT NULL ENABLE ,
      "KEYWORD_TWO"   VARCHAR2(200 CHAR) NOT NULL ENABLE ,
      "KEYWORD_THREE" VARCHAR2(200 CHAR) NOT NULL ENABLE ,
      CONSTRAINT "SEARCH_PROPERTY_PK" PRIMARY KEY ("SEARCH_ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "SYSTEM" ENABLE
    )
    SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
    (
      INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    )
    TABLESPACE "SYSTEM" ;
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."SEARCH_ID"
IS
  'Keresés azonosító';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."CLIENT_ID"
IS
  'Ügyfél azonosító';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."PROPERTY_TYPE"
IS
  'Ingatlan típus';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."SIZE_MIN"
IS
  'Minimum alapterület ';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."SIZE_MAX"
IS
  'Maximum alapterület ';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."PRICE_MIN"
IS
  'Minimum ár';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."PRICE_MAX"
IS
  'Maximum alapterület ';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."SEARCH_TYPE"
IS
  'Eladó vagy kiadó';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."CITY"
IS
  'Város';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."KEYWORD_ONE"
IS
  'Kulcsszó 1';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."KEYWORD_TWO"
IS
  'Kulcsszó 2';
  COMMENT ON COLUMN "ADMIN"."SEARCH_PROPERTY"."KEYWORD_THREE"
IS
  'Kulcsszó 3';
CREATE OR REPLACE FORCE VIEW "ADMIN"."SALE_VW"
  (
    "NAME", "SALE_STATISTICS"
  )
AS
  SELECT UD.NAME ,
    COUNT(*) AS SALE_STATISTICS
  FROM PROPERTY P
  JOIN USER_DATA UD
  ON P.USER_ID       = UD.USER_ID
  WHERE P.AD_STATUS IN ('Eladva' ,'Kiadva')
  GROUP BY UD.NAME
  ORDER BY UD.NAME ;
CREATE OR REPLACE FORCE VIEW "ADMIN"."VIEW_COUNTER_VW" ("PROPERTY_ID", "COUNT_NUMBER")
AS
  SELECT P.PROPERTY_ID ,
    P.COUNT_NUMBER
  FROM PROPERTY P
  WHERE P.COUNT_NUMBER != 0
  ORDER BY P.COUNT_NUMBER ;
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PROPERTY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEARCH_PROPERTY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CLIENT_SEQ START WITH 1 INCREMENT BY 1;
  INSERT
  INTO USER_DATA COLUMNS
    (
      USER_ID ,
      NAME ,
      PASSWORD ,
      EMAIL ,
      STATUS
    )
    VALUES
    (
      1 ,
      'admin' ,
      '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918' ,
      'admin@ingatlan.hu' ,
      'ACTIVE'
    ) ;