package Document;

public class DocumentTemplate {

	public static String SALE = "                                                   Ingatlan adásvételi szerződés\r\n\r\n"
			+ "Amely készült, egyrészről %s mint Eladó, másrészről %s, mint Vevő között az alulírott napon az alábbi feltételek mellett:\r\n\r\n"
			+ "1./\r\n"
			+ "Szerződő felek megállapítják, hogy Eladó kizárólagos tulajdonát képezi a per-,teher- és igénymentes %s %s sz. alatti %d m\u00B2 "
			+ "területű ingatlan, amelyre a felek adásvételi szerződést kívánnak kötni az alábbiak szerint.\r\n\r\n"
			+ "Az adásvételi szerződés megkötésének feltétele, hogy Vevő az Új Széchenyi Terv keretében kombinált mikrohitelben részesüljön.\r\n\r\n"
			+ "2./\r\n"
			+ "A fenti ingatlan vételárára: %d M forint, azzal, hogy az adásvételi szerződéssel felmerülő összes költségeket Vevő köteles megfizetni.\r\n\r\n"
			+ "Eladó szavatolja az ingatlan per-, teher- és igénymentességét. Nyilatkozik arról is, hogy a társasházi törzslapon teher bejegyezve – "
			+ "legjobb tudomása szerint – nincs. Vevő a fentieknek megfelelően tehermentes ingatlant vásárol, vételi ajánlata csakis ennek megfelelő.\r\n\r\n"
			+ "3./\r\n"
			+ "Szerződő Felek megállapodnak abban, hogy a vételárat Vevő az alábbiak szerint fizeti meg Eladó részére:\r\n"
			+ "-	 %s (dátum) napján a vételár előleget fizet (amely összeg megegyezik a kombinált mikrohitel program önrészével),\r\n"
			+ "-	Az adásvételi szerződés megkötésének napján kifizeti a vételár %s -át (amely a vissza nem térítendő támogatással "
			+ "megegyező összeg), ez az összeg ugyancsak vételárelőleg.\r\n\r\n"
			+ "A vételárelőlegek megfizetése és a mikrohitel összegének kifizetése a szerződést szerkesztő Dr. Zug ügyvéd számlájára átutalással történik.\r\n\r\n"
			+ "     ……………………	                                                           ……………………\r\n"
			+ "         	       Eladó	                                                                                   Vevő\r\n"
			+ "\r\nA hiteligénylés, vagy a vissza nem térítendő pályázati rész sikertelensége esetén a vételár előlegek Vevőnek visszajárnak.\r\n\r\n"
			+ "A mikrohitel felvételének sikeressége esetén a teljes vételárat letéteményes ügyvéd köteles a mikrohitel átutalását "
			+ "követő 3 munkanapon belül Eladó számlájára kiutalni.\r\n\r\n"
			+ "4./\r\n"
			+ "Szerződő felek megállapodnak abban, hogy a kölcsön folyósítását követően egyik fél sem jogosult a jelen szerződést "
			+ "módosítani, a szerződéstől elállni, vagy a szerződést bármilyen módon megszüntetni. Ezek a jogok csak abban "
			+ "az esetben gyakorolhatók, ha ehhez a hitelközvetítő írásban hozzájárult.\r\n\r\n"
			+ "5./\r\n"
			+ "Szerződő felek megállapodnak abban, hogy Vevő a vételár teljes megfizetésének napján lép az ingatlan birtokába "
			+ "és attól kezdve húzza annak hasznait és viseli terheit. A közüzemi díjakat a birtokbaadás napjáig Eladó köteles "
			+ "viselni, Felek a fogyasztásmérők állását a birtokba lépéssel egyidejűleg leolvassák és a szolgáltatók felé lejelentik. "
			+ "Eladó köteles igazolni, hogy közös költség tartozása a birtokbavétel napján nem áll fenn.\r\n\r\n"
			+ "6./\r\n"
			+ "Szerződő felek kijelentik, hogy Eladó belföldön lakó magyar állampolgár, Vevő bejegyzett és működő gazdasági társaság, "
			+ "akiknek ingatlan elidegenítési- és szerzési képességét jogszabály vagy határozat nem korlátozza.\r\n\r\n"
			+ "7./\r\n"
			+ "Szerződő felek, hozzájárulnak ahhoz, hogy a hitelösszeg folyósítása esetén a hitelközvetítő javára "
			+ "a mikrohitel és járulékai erejéig a jelzálogjog az adásvétel tárgyát képező ingatlanokra a Földhivatal "
			+ "ingatlan-nyilvántartásába bejegyzésre kerüljön.\r\n\r\n"
			+ "Figyelemmel arra, hogy az adásvételi szerződés érvényességi feltétele a mikrohitel folyósítása, "
			+ "Eladó a teljes vételár felvételével külön nyilatkozatban járul hozzá ahhoz, hogy Vevő tulajdonjoga "
			+ "az 1. pontban megjelölt ingatlanra a Körzeti Földhivatal ingatlan- nyilvántartásába adásvétel "
			+ "jogcímén bejegyzésre kerüljön. Ezért szerződő felek a tulajdonjog bejegyzését kérő beadványuk "
			+ "elintézésének függően tartását kérik, legfeljebb 6 hónapra.\r\n\r\n"
			+ "Eladó az adásvételi szerződés aláírásával egyidejűleg a folyamatos ügyintézés érdekében a tulajdonjog "
			+ "bejegyzéséről szóló hozzájáruló nyilatkozatát aláírja, és azt három eredeti példányban ügyvédnél letétbe "
			+ "helyezi. Ezen nyilatkozatot szerződést szerkesztő ügyvéd akkor nyújthatja be a Földhivatalba, "
			+ "amikor a teljes vételárat átutalta Eladó fenti számlájára. \r\n\r\n"
			+ "Felek tudomással bírnak arról, hogy az előszerződést a Földhivatalba benyújtani nem lehet, de kötelesek "
			+ "ennek alapján az adásvételi szerződést megkötni.\r\n\r\n"
			+ "     ……………………	                                                           ……………………\r\n"
			+ "         	       Eladó	                                                                                   Vevő";
	
	public static final String RENTAL = "                                                   Bérleti szerződés\r\n\r\n"
			+ "Amely létrejött egyrészről %s mint bérbeadó, (továbbiakban bérbeadó) másrészről pedig %s mint bérlő, (továbbiakban bérlő) "
			+ "között alulírt napon és helyen a továbbiak szerint: \r\n\r\n"
			+ "1.	 Bérbeadó %s. napjától a %s %s szám alatt található %s m\u00B2 ingatlant bérbeadónak. \r\n\r\n"
			+ "2.	 Szerződő felek a bérleti szerződést határozatlan időre kötik. \r\n\r\n"
			+ "3.	 Szerződő felek megállapodnak abban, hogy az ingatlan után bérlő %d hó bérleti díjat köteles fizetni bérbeadónak, "
			+ "minden hónap 15. napjáig, a kibocsátott számla ellenében, átutalás formájában, a bérbeadó számlájára. "
			+ "Felek rögzítik, hogy a bérleti díj tartalmazza a bérbeadó által fizetendő forrás adó összegét is. A bérlő köteles ezen kívül a "
			+ "rezsi költségéet minden hónapban fizetni, amely magában foglalja a közmű szolgáltatások díját.\r\n\r\n"
			+ "4.	 A bérlő bérbeadó részére jelen szerződés aláírásával egyidejűleg kézpénzben átad %d hónap bérleti díjnak "
			+ "megfelelő kauciót akként, hogy a kaució nem tartalmazza a forrás adó összegét. Bérbeadó a fenti összeg átvételét elismeri és nyugtázza.\r\n\r\n"
			+ "5.	 Felek rögzítik, hogy a kaució összegével a bérleti szerződés megszűnése esetén egymással elszámolnak. "
			+ "A kaucióból a szerződés megszűnése esetén bérbeadó levonhatja az esetlegesen elmaradt bérleti díjakat, az azok "
			+ "után számított késedelmi kamatot, valamint a be nem fizetett rezsi költségeket, azok kamatait, továbbá a bérleményben "
			+ "okozott kárt is. A fentiek után fennmaradó összeget bérlő részére bérbeadó elszámolás keretében köteles megfizetni. "
			+ "Bérbeadó tudomásul veszi ugyanakkor, hogy a kaució kifejezetten a bérleti szerződés megszűnése esetére a ki nem fizetett "
			+ "bérleti díjak, rezsi költségek és károk helyreállításának költsége és biztosításaként szolgál, ezért ezt az összeget saját célra nem használhatja fel.\r\n\r\n"
			+ "6.	 A bérlemény kizárólagos használatára a bérlő jogosult. A bérbeadó kijelenti, hogy az ingatlant másnak bérbe illetve "
			+ "használatba nem adta, senkinek olyan jogot nem engedélyezett, amely bérlő használatát bármilyen formában korlátozná. \r\n\r\n"
			+ "7.	 Bérlő kötelezettséget vállal arra, hogy a bérleti szerződés időtartama alatt a bérleti díjon kívül az ingatlan valamennyi "
			+ "költségét viseli - amely magában foglalja a közüzemi díjakat, víz villany gáz, és az esetleg felmerülő egyéb költségeket is. "
			+ "Miután a bérlő gazdasági társaság, ezért az általa fizetett közüzemi díjakat és egyéb költségeket elszámolhatja, ezért "
			+ "bérbeadó jelen szerződés aláírásával kifejezetten hozzájárul ahhoz, hogy bérlő a közüzemi szolgáltatóknál, illetve egyéb "
			+ "szolgáltatást nyújtó társaságoknál szolgáltatási szerződést kössön a bérlet időtartamára a saját nevére. A bérleti jogviszony "
			+ "megszűnése esetén pedig bérlő kötelezettséget vállal arra vonatkozóan, hogy a közüzemi és egyéb szolgáltatási szerződéseket megszűnteti. \r\n\r\n"
			+ "8.	 A bérlő a bérleményt köteles rendeltetésszerűen használni, azt rendszeresen karbantartani, a szokásos és rendeltetésszerű "
			+ "használattal felmerülő javítási, valamint kisebb felújítási munkálatokat pedig saját költségén elvégezni. A bérlő a bérleményen "
			+ "átalakítási munkálatokat csak bérbeadó előzetes írásbeli hozzájárulásával végezhet, azzal, hogy a bérleti jogviszony megszűnése "
			+ "esetén köteles az eredeti állapotot helyreállítani, kivéve ha bérbeadóval az írásban kötött megállapodása más kötelezettséget "
			+ "jelöl meg. Bérlő köteles az ingatlanra vagyonvédelmi biztosítást kötni. \r\n\r\n"
			+ "9.	 Bérbeadó jogosult arra, hogy előzetes értesítés után a bérlemény rendeltetésszerű használatát ellenőrizze, tovább arra is,"
			+ " hogy a közüzemi és egyéb szolgáltatási díjak rendszeres befizetését ellenőrizze. \r\n\r\n"
			+ "10.	 Szerződő felek megállapodnak abban, hogy a fenti szerződést bármelyik fél 30 napos felmondási idővel írásban gyakorolhatja a másik fél felé. \r\n\r\n"
			+ "11.	 Azonnali hatállyal felmondásnak van helye abban az esetben, hogyha bármelyik fél a szerződésben írt kötelezettségeket megszegi, "
			+ "illetve a bérlő a bérleti díjat, illetve a közüzemi és egyéb szolgáltatási díjakat egyszerű írásbeli felszólítás ellenére sem fizeti meg.\r\n\r\n"
			+ "12.	 Bérlő kötelezettséget vállal arra, hogy a bérleti szerződés megszűnésekor az ingatlant haladéktalanul bérbeadó birtokába adja, ugyanolyan "
			+ "állapotban, mint amilyen állapotban birtokba vette. A bérlő tudomásul veszi, hogy a bérleményben található ingóságaira bérbeadói zálogjog "
			+ "illeti meg arra az esetre, hogyha a bérleti díj és egyéb közüzemi vagy szolgáltatási díj tartozása az általa átadott kaució összegét meghaladja.\r\n\r\n"
			+ "13.	 Abban az esetben, ha a bérlő a szerződés megszűnésekor bérbeadó birtokába nem adja, akkor a jogtalan használat idejére a bérleti "
			+ "szerződés háromszorosát köteles használati díjként fizetni. \r\n\r\n"
			+ "14.	 Szerződő felek kijelentik, hogy a bérleményt bérlő harmadik személynek albérletbe vagy használatba csak bérbeadó kifejezett írásbeli hozzájárulásával adhatja. \r\n\r\n"
			+ "15.	 Bérbeadó kijelenti, hogy külön írásbeli engedéllyel bérlő részére hozzájárulást ad ahhoz, hogy a bérleményt bérlő a Fővárosi Cégbíróságnál "
			+ "székhelyként, telephelyként vagy esetleg fióktelepként feltűntethesse. \r\n\r\n"
			+ "16.	 Szerződő felek kijelentik, hogy a jelen szerződésben nem szabályozott kérdésekre a Polgári Törvénykönyv valamint a lakások és helységek "
			+ "bérletére vonatkozó 1993. évi XVIII-as törvény rendelkezései tartják irányadónak.\r\n\r\n"
			+ "17.	 Szerződő felek kijelentik, hogy egymással kapcsolatos vitájukat elsősorban peren kívül próbálják rendezni, ennek eredménytelensége "
			+ "esetére kikötik a Bíróság kizárólagos illetékességét. \r\n\r\n" 
			+ "A fenti bérleti szerződést elolvasás után, mint akaratunkkal mindenben egyezőt írtuk alá. \r\n\r\n" 
			+ "Kelt, Budapest, %s.\r\n\r\n" + "     ……………………	                                                           ……………………\r\n"
			+ "         	       Eladó	                                                                                   Vevő";
	
}
